### ISSUE TITLE
공통 헤더 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by kimmjae99** [jeju-deers/jeju-deers-frontend#12]
## 💼 작업 설명

공통 헤더 컴포넌트 UI를 구현합니다.

## ✅ TODO

공통 헤더 컴포넌트를 구현하는데 각각의 탭바에 해당하는 UI도 구현합니다.

- [x] 헤더 컴포넌트 생성 후 각각의 탭바 설정
- [x] 각각의 탭바에 경로 설정 및 추가적인 UI 디자인(hover 시)
- [x] 탭바 hover시 해당 탭바에 있는 카테고리 출력
