### ISSUE TITLE
파일 절대경로 설정

### ISSUE THREAD

**Issue by kimmjae99** [jeju-deers/jeju-deers-frontend#14]
## 💼 작업 설명

프로젝트 내 파일들의 절대경로를 설정합니다.

## ✅ TODO

프로젝트 내 작업하는 파일들에 접근하는 경로를 절대경로로 표시합니다.

- [x] tsconfig.json 작성
- [x] vite.config.ts 작성
- [x] 파일 절대경로 설정
