### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by HY219** [jeju-deers/jeju-deers-frontend#25]
## 💼 작업 설명

- 회원가입 페이지인 SignUpPage에서 작성한 데이터를 서버로 넘겨줘야합니다.

## ✅ TODO

- [x] react-query 설치
- [x] react-query-devtools 설치
- [x] SignUpPage에서 작성한 데이터 서버로 전달
  - [x] 가입 목적에 따라 데이터 전달
  - `외부인(external), 선수(player), 코치 및 스탭(coach)`
- [ ] 회원가입 시 조건 추가
  * 아이디, 이름, 닉네임, 이메일 : 한글, 영어, 숫자, 특수문자
  * 비밀번호 : 한글, 영어, 숫자
  * 출신학교, 담당 : 한글
  * 학번, 백넘버  : 숫자
  * 포지션 : 영어

## ❕기타

- 코치 및 스탭에 대한 이름을 `coach/member/coachesStaff` 세 가지 중 하나로 정하면 좋을 것 같아요:)
  - `coach` 로 결정되었습니다~

- 회원가입 UI 구현 시 `외부인`과 `선수`에 대해 지정한 이름을 서버 이름과 동일하게 변경하려고 합니다:)
  -  `outsider, roaster` -> `external, player`
