### ISSUE TITLE
userType별 명단 불러오기 구현

### ISSUE THREAD

**Issue by kimmjae99** [jeju-deers/jeju-deers-frontend#45]
## 💼 작업 설명

userType별로 명단 GET 해오는 기능 구현

## ✅ TODO

- [x] 명단리스트 데이터 구성 확인
- [x] userType별로 리스트 GET 하기
- [x] react-query써서 hook으로 적용하기
