### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by kimmjae99** [jeju-deers/jeju-deers-frontend#5]
## 💼 작업 설명

프로젝트 세팅

필요한 패키지들 설치
- styled-components
- tailwindCSS
- tailwind-styled-components
- twin.macro
- babel-plugin
- eslint
- prettier
- husky

디렉토리 구조 파악을 위해 디렉토리를 생성해두고 임시파일을 넣어두겠습니다.
개발할 땐 지우고 개발하시면 됩니다.

## ✅ TODO

- [ ] 필요한 패키지 설치
  - [ ] styled-components
  - [ ] tailwindCSS
  - [ ] tailwind-styled-components
  - [ ] twin.macro
  - [ ] babel-plugin
  - [ ] eslint
  - [ ] prettier
  - [ ] husky
- [ ] 디렉토리 구조 파악
디렉토리 구조 파악을 위해 디렉토리를 생성해두고 임시파일을 넣어두겠습니다.
개발할 땐 지우고 개발하시면 됩니다.

## ❕기타

위에 해당하는 패키지 말고 사용되는 패키지가 있는 경우 말씀해주세요
