### ISSUE TITLE
게시물 상세 페이지 UI 구현

### ISSUE THREAD

**Issue by HY219** [jeju-deers/jeju-deers-frontend#51]
## 💼 작업 설명

- 게시물 상세 페이지 UI 구현

## ✅ TODO

- [x] 게시물 상세 UI
  - [x] 게시판 카테고리
    ![image](https://github.com/user-attachments/assets/aa1ee548-64b2-4c80-a069-a76639acca8f)
  - [x] 제목
  - [x] 작성자, userType ( 매니저, 소속(OB,YB) )
  - [x] 조회수, 댓글수
  - [x] 작성 시간
  - [x] 내용
  - [x] 스크롤
  - [x] 이전글, 다음글, ~~등록~~ 버튼
    - [x] 등록 버튼 제거 
  - [x] 목록, TOP

- [x] 댓글 목록 UI
  - [x] 작성자, userType ( 매니저, 코치, 소속(OB,Y,B), 외부인 )
  - [x] 작성 시간

- [x] 댓글 작성 UI
  - [x] 작성자
  - [x] 글 작성 창
  - [x] 등록 버튼
  - [x] 스크롤

## ❕기타

![image](https://github.com/user-attachments/assets/3aebad56-3e95-422d-b15e-63c6628da6b2)
