### ISSUE TITLE
단일 게시물 조회 기능 구현

### ISSUE THREAD

**Issue by HY219** [jeju-deers/jeju-deers-frontend#54]
## 💼 작업 설명

- 게시물 상세 페이지에서, 단일 게시물 조회 기능 구현

## ✅ TODO

- [x] 단일 게시물 조회 api 구현
  - [x] `/board/:id` GET 요청
    - [x] 게시물이 작성된 게시판 이름
      - [x] 게시물 type과 일치하는 text 출력 및 링크 지정
    - [x] 제목 (title)
    - [ ] 작성자 이름, 소속 (owner, belong)
    - [x] 작성 시간 (createdAt)
    - [x] 조회수 (views)
    - [x] 내용 (content)

## ❕기타

- '글 작성자의 소속'과 '댓글수'에 대한 데이터를 백엔드에서 제공받아야 할 것 같아 확인이 필요합니다.
- '이미지', '비디오'에 대한 응답도 확인 필요

- 아래는 **단일 게시물 조회에 대한 응답 데이터**입니다.
![image](https://github.com/user-attachments/assets/68048bf0-b285-44c6-965f-8d77884d545b)

- 아래는 **게시물 상세페이지 UI**입니다.
![image](https://github.com/user-attachments/assets/3aebad56-3e95-422d-b15e-63c6628da6b2)
