### ISSUE TITLE
게시판 상세페이지 내 댓글 조회 기능 구현

### ISSUE THREAD

**Issue by HY219** [jeju-deers/jeju-deers-frontend#56]
## 💼 작업 설명

임시 댓글 데이터를 이용해 게시판 상세페이지 내 댓글 조회 기능 구현

## ✅ TODO

- [ ] 임시 댓글 목록 데이터 생성
  - [ ] 댓글을 작성한 유저의 닉네임 & 소속
  - [ ] 댓글 내용
  - [ ] 댓글을 작성한 날짜(연,월,일) & 시간
- [ ] 댓글 조회 기능 구현
  - [ ] 리스트 형식으로 댓글 목록 출력
  - [ ] 임시 데이터를 이용해, UI 형식에 맞춰 출력

## ❕기타

![image](https://github.com/user-attachments/assets/db4357ee-58f2-4ea0-b34a-5d5f6d26d5a8)
