### ISSUE TITLE
관리자 페이지 UI 구현

### ISSUE THREAD

**Issue by HY219** [jeju-deers/jeju-deers-frontend#60]
## 💼 작업 설명

- 관리자 페이지 UI 구현

## ✅ TODO

- [ ] 사용자 정보 목록
  - [ ] 이름, 소속, 역할, 권한, 수정날짜
- [ ] 검색
- [ ] 회원 삭제 버튼
- [ ] 정보 수정 버튼
- [ ] 저장, 나가기 버튼

## ❕기타

- 저장 버튼, 검색 기능, 수정날짜, 사진 UI에 대해서 디자인 팀과 논의가 필요합니다.

![image](https://github.com/user-attachments/assets/1e2181c3-08d9-4d2f-97db-f2e072679e4a)
